### ISSUE TITLE
Emotes

### ISSUE THREAD

**Issue by Eight8-7020** [JamesHawkinss/discord-channel-sync#1]
This works great! But one thing that is annoying me is that the emotes just end up as :sadkek: or whatever instead of the actual emote. Is there any way to fix this?

**Comment by Eight8-7020** [comment]
And also deleting the message when it is deleted in the original server would be a nice addition too

**Comment by Eight8-7020** [comment]
Thanks I solved it

**Comment by JamesHawkinss** [comment]
Glad to hear you resolved the issue! :D
